food = input("Name a food >")
plant = input("Name a type of plant >")
cookingMethod = input("Name a method of cooking >")
burnedfood = input("What word describe burned food? >")
DIY = input("Name a DIY item >")
print("MENU")
print(cookingMethod,food,"with",burnedfood, plant,"on a bed of",DIY )
